// Mock data for newsletters
export const mockNewsletters = [
  {
    id: "newsletter1",
    name: "Tech Weekly",
    url: "https://techweekly.com",
    description: "A weekly roundup of the latest technology news and trends.",
    subscribers: 25000,
    frequency: "Weekly",
    category: "Technology",
    lastUpdated: "2023-06-18T10:30:00Z",
    articles: [
      {
        id: "article1",
        title: "The Rise of AI in Everyday Applications",
        summary:
          "How artificial intelligence is becoming integrated into our daily lives through various applications and services.",
        publishedAt: "2023-06-15T08:00:00Z",
        readCount: 12500,
        likeCount: 850,
        tags: ["AI", "Technology", "Innovation"],
      },
      {
        id: "article2",
        title: "Web Development Trends to Watch in 2023",
        summary: "Exploring the emerging trends and technologies that are shaping the future of web development.",
        publishedAt: "2023-06-08T09:15:00Z",
        readCount: 9800,
        likeCount: 720,
        tags: ["Web Development", "Trends", "Programming"],
      },
      {
        id: "article3",
        title: "The Future of Remote Work in Tech",
        summary:
          "How technology companies are adapting to remote work and what this means for the future of the industry.",
        publishedAt: "2023-06-01T10:30:00Z",
        readCount: 15200,
        likeCount: 1100,
        tags: ["Remote Work", "Tech Industry", "Future of Work"],
      },
    ],
  },
  {
    id: "newsletter2",
    name: "Business Insights",
    url: "https://businessinsights.com",
    description: "In-depth analysis of business trends, strategies, and market developments.",
    subscribers: 18500,
    frequency: "Bi-weekly",
    category: "Business",
    lastUpdated: "2023-06-15T14:45:00Z",
    articles: [
      {
        id: "article4",
        title: "How Startups Are Navigating Economic Uncertainty",
        summary: "Strategies that successful startups are employing to thrive despite economic challenges.",
        publishedAt: "2023-06-14T11:00:00Z",
        readCount: 8700,
        likeCount: 620,
        tags: ["Startups", "Economy", "Business Strategy"],
      },
      {
        id: "article5",
        title: "The Evolution of E-commerce in a Post-Pandemic World",
        summary: "How online shopping has transformed and what businesses need to know to stay competitive.",
        publishedAt: "2023-06-01T09:30:00Z",
        readCount: 10500,
        likeCount: 780,
        tags: ["E-commerce", "Retail", "Digital Transformation"],
      },
    ],
  },
  {
    id: "newsletter3",
    name: "AI Frontiers",
    url: "https://aifrontiers.com",
    description: "Exploring the cutting edge of artificial intelligence research and applications.",
    subscribers: 12000,
    frequency: "Monthly",
    category: "Artificial Intelligence",
    lastUpdated: "2023-06-10T16:20:00Z",
    articles: [
      {
        id: "article6",
        title: "Breakthroughs in Natural Language Processing",
        summary: "Recent advances in NLP that are pushing the boundaries of what AI can understand and generate.",
        publishedAt: "2023-06-10T13:45:00Z",
        readCount: 7200,
        likeCount: 540,
        tags: ["NLP", "AI Research", "Machine Learning"],
      },
      {
        id: "article7",
        title: "Ethical Considerations in AI Development",
        summary:
          "The important ethical questions that researchers and companies must address as AI becomes more powerful.",
        publishedAt: "2023-05-15T10:20:00Z",
        readCount: 9100,
        likeCount: 820,
        tags: ["AI Ethics", "Technology Ethics", "Responsible AI"],
      },
      {
        id: "article8",
        title: "AI in Healthcare: Current Applications and Future Potential",
        summary: "How artificial intelligence is transforming healthcare and what innovations are on the horizon.",
        publishedAt: "2023-04-20T09:10:00Z",
        readCount: 11500,
        likeCount: 950,
        tags: ["Healthcare", "AI Applications", "Medical Technology"],
      },
    ],
  },
]

// Mock RSS sources
export const mockRssSources = [
  {
    id: "source1",
    name: "TechCrunch",
    url: "https://techcrunch.com/feed/",
    feedUrl: "https://techcrunch.com/feed/",
    category: "Technology",
    lastFetched: "2023-05-15T08:30:00Z",
    articleCount: 42,
    active: true,
  },
  {
    id: "source2",
    name: "CSS Tricks",
    url: "https://css-tricks.com",
    feedUrl: "https://css-tricks.com/feed/",
    category: "Web Development",
    lastFetched: "2023-05-14T14:15:00Z",
    articleCount: 28,
    active: true,
  },
  {
    id: "source3",
    name: "React Newsletter",
    url: "https://reactnewsletter.com",
    feedUrl: "https://reactnewsletter.com/feed",
    category: "JavaScript",
    lastFetched: "2023-05-10T22:10:00Z",
    articleCount: 15,
    active: true,
  },
  {
    id: "source4",
    name: "System Design Weekly",
    url: "https://systemdesignweekly.com",
    feedUrl: "https://systemdesignweekly.com/feed",
    category: "System Design",
    lastFetched: "2023-05-12T11:45:00Z",
    articleCount: 8,
    active: true,
  },
  {
    id: "source5",
    name: "Database Weekly",
    url: "https://databaseweekly.com",
    feedUrl: "https://databaseweekly.com/feed",
    category: "Databases",
    lastFetched: "2023-05-13T09:20:00Z",
    articleCount: 12,
    active: true,
  },
]

// Mock publishing platforms
export const mockPublishingPlatforms = [
  {
    id: "platform1",
    name: "Substack",
    type: "newsletter",
    connected: true,
    lastPublished: "2023-05-01T14:30:00Z",
    publishCount: 8,
  },
  {
    id: "platform2",
    name: "Medium",
    type: "blog",
    connected: true,
    lastPublished: "2023-04-28T10:15:00Z",
    publishCount: 12,
  },
  {
    id: "platform3",
    name: "Twitter",
    type: "social",
    connected: true,
    lastPublished: "2023-05-15T09:45:00Z",
    publishCount: 24,
  },
  {
    id: "platform4",
    name: "LinkedIn",
    type: "social",
    connected: true,
    lastPublished: "2023-05-10T16:20:00Z",
    publishCount: 18,
  },
  {
    id: "platform5",
    name: "Notion",
    type: "workspace",
    connected: false,
    lastPublished: null,
    publishCount: 0,
  },
  {
    id: "platform6",
    name: "Email List",
    type: "email",
    connected: true,
    lastPublished: "2023-05-05T11:30:00Z",
    publishCount: 6,
  },
]

// Mock integrations
export const mockIntegrations = [
  {
    id: "integration1",
    name: "Airtable",
    type: "database",
    connected: true,
    lastSynced: "2023-05-15T08:30:00Z",
    recordCount: 156,
  },
  {
    id: "integration2",
    name: "Google Sheets",
    type: "spreadsheet",
    connected: true,
    lastSynced: "2023-05-14T14:15:00Z",
    recordCount: 98,
  },
  {
    id: "integration3",
    name: "Notion",
    type: "workspace",
    connected: true,
    lastSynced: "2023-05-13T22:10:00Z",
    recordCount: 42,
  },
  {
    id: "integration4",
    name: "Google Drive",
    type: "storage",
    connected: true,
    lastSynced: "2023-05-12T11:45:00Z",
    recordCount: 75,
  },
  {
    id: "integration5",
    name: "Dropbox",
    type: "storage",
    connected: false,
    lastSynced: null,
    recordCount: 0,
  },
]
