// Mock videos data
export const mockVideos = [
  {
    id: "1",
    title: "How AI is Transforming Content Creation in 2023",
    description:
      "Explore the latest AI tools and techniques that are revolutionizing content creation across industries.",
    thumbnail: "/placeholder.svg?height=720&width=1280",
    views: 15420,
    likes: 1200,
    commentCount: 89,
    duration: "18:24",
    publishedAt: "2023-05-15T14:30:00Z",
    channel: {
      id: "channel1",
      name: "Future Tech Insights",
      thumbnail: "/placeholder.svg?height=100&width=100",
    },
    tags: ["AI", "Content Creation", "Technology"],
    watched: true,
    saved: true,
    engagement: 0.78,
    transcript: "Today we're diving into how artificial intelligence is completely transforming content creation...",
  },
  {
    id: "2",
    title: "The Complete Guide to Content Repurposing",
    description: "Learn how to maximize your content's reach by repurposing it across multiple platforms.",
    thumbnail: "/placeholder.svg?height=720&width=1280",
    views: 8750,
    likes: 950,
    commentCount: 62,
    duration: "22:15",
    publishedAt: "2023-06-02T10:15:00Z",
    channel: {
      id: "channel2",
      name: "Content Strategy Pro",
      thumbnail: "/placeholder.svg?height=100&width=100",
    },
    tags: ["Content Strategy", "Marketing", "Social Media"],
    watched: false,
    saved: true,
    engagement: 0.65,
    transcript: "Content repurposing is one of the most effective strategies for maximizing your ROI...",
  },
  {
    id: "3",
    title: "5 Advanced YouTube Growth Strategies",
    description: "Discover advanced techniques to grow your YouTube channel and increase engagement.",
    thumbnail: "/placeholder.svg?height=720&width=1280",
    views: 12300,
    likes: 1050,
    commentCount: 78,
    duration: "15:42",
    publishedAt: "2023-06-10T16:45:00Z",
    channel: {
      id: "channel3",
      name: "Creator Academy",
      thumbnail: "/placeholder.svg?height=100&width=100",
    },
    tags: ["YouTube", "Channel Growth", "Content Creation"],
    watched: true,
    saved: false,
    engagement: 0.72,
    transcript:
      "Today I'm sharing five advanced strategies that helped me grow my channel to over 500,000 subscribers...",
  },
  {
    id: "4",
    title: "The Future of Digital Marketing: Trends to Watch",
    description: "Stay ahead of the curve with these emerging digital marketing trends that will shape the industry.",
    thumbnail: "/placeholder.svg?height=720&width=1280",
    views: 9800,
    likes: 820,
    commentCount: 54,
    duration: "20:18",
    publishedAt: "2023-06-18T09:30:00Z",
    channel: {
      id: "channel4",
      name: "Digital Marketing Insights",
      thumbnail: "/placeholder.svg?height=100&width=100",
    },
    tags: ["Digital Marketing", "Trends", "Strategy"],
    watched: false,
    saved: false,
    engagement: 0.61,
    transcript: "The digital marketing landscape is constantly evolving, and staying ahead of trends is crucial...",
  },
  {
    id: "5",
    title: "How to Create Viral Social Media Content",
    description: "Learn the psychology behind viral content and how to create posts that get shared.",
    thumbnail: "/placeholder.svg?height=720&width=1280",
    views: 18500,
    likes: 1650,
    commentCount: 112,
    duration: "16:55",
    publishedAt: "2023-06-25T13:20:00Z",
    channel: {
      id: "channel5",
      name: "Social Media Mastery",
      thumbnail: "/placeholder.svg?height=100&width=100",
    },
    tags: ["Social Media", "Viral Content", "Marketing"],
    watched: true,
    saved: true,
    engagement: 0.85,
    transcript: "Creating viral content isn't just about luck. There's a science behind what makes people share...",
  },
  {
    id: "6",
    title: "Content Creation Tools Every Creator Needs in 2023",
    description: "A comprehensive review of the best tools for content creators this year.",
    thumbnail: "/placeholder.svg?height=720&width=1280",
    views: 11200,
    likes: 980,
    commentCount: 73,
    duration: "24:10",
    publishedAt: "2023-07-05T11:45:00Z",
    channel: {
      id: "channel6",
      name: "Creator Toolkit",
      thumbnail: "/placeholder.svg?height=100&width=100",
    },
    tags: ["Tools", "Content Creation", "Productivity"],
    watched: false,
    saved: true,
    engagement: 0.69,
    transcript:
      "Having the right tools can make or break your content creation workflow. Today I'm sharing my top picks...",
  },
  {
    id: "7",
    title: "The Art of Storytelling in Content Marketing",
    description: "Discover how to use storytelling techniques to create more engaging and effective content.",
    thumbnail: "/placeholder.svg?height=720&width=1280",
    views: 7900,
    likes: 720,
    commentCount: 48,
    duration: "19:35",
    publishedAt: "2023-07-12T15:10:00Z",
    channel: {
      id: "channel7",
      name: "Content Marketing Masters",
      thumbnail: "/placeholder.svg?height=100&width=100",
    },
    tags: ["Storytelling", "Content Marketing", "Engagement"],
    watched: true,
    saved: false,
    engagement: 0.58,
    transcript:
      "Storytelling is one of the most powerful tools in a content marketer's arsenal. Today we'll explore...",
  },
  {
    id: "8",
    title: "SEO Strategies That Actually Work in 2023",
    description: "Cut through the noise and learn which SEO strategies are delivering results this year.",
    thumbnail: "/placeholder.svg?height=720&width=1280",
    views: 14300,
    likes: 1150,
    commentCount: 92,
    duration: "21:48",
    publishedAt: "2023-07-20T08:55:00Z",
    channel: {
      id: "channel8",
      name: "SEO Experts",
      thumbnail: "/placeholder.svg?height=100&width=100",
    },
    tags: ["SEO", "Digital Marketing", "Strategy"],
    watched: false,
    saved: true,
    engagement: 0.74,
    transcript: "SEO is constantly evolving, and what worked last year might not work today. Let's dive into...",
  },
  {
    id: "9",
    title: "How to Build a Personal Brand Online",
    description: "A step-by-step guide to building and growing your personal brand in the digital space.",
    thumbnail: "/placeholder.svg?height=720&width=1280",
    views: 10600,
    likes: 940,
    commentCount: 67,
    duration: "23:22",
    publishedAt: "2023-07-28T12:40:00Z",
    channel: {
      id: "channel9",
      name: "Brand Building Academy",
      thumbnail: "/placeholder.svg?height=100&width=100",
    },
    tags: ["Personal Branding", "Career Development", "Social Media"],
    watched: true,
    saved: true,
    engagement: 0.71,
    transcript:
      "Your personal brand is one of your most valuable assets in today's digital economy. Let's talk about...",
  },
  {
    id: "10",
    title: "Content Analytics: Measuring What Matters",
    description: "Learn how to track and analyze the right metrics to improve your content performance.",
    thumbnail: "/placeholder.svg?height=720&width=1280",
    views: 8100,
    likes: 780,
    commentCount: 51,
    duration: "17:15",
    publishedAt: "2023-08-05T14:15:00Z",
    channel: {
      id: "channel10",
      name: "Data-Driven Content",
      thumbnail: "/placeholder.svg?height=100&width=100",
    },
    tags: ["Analytics", "Content Strategy", "Data"],
    watched: false,
    saved: false,
    engagement: 0.63,
    transcript:
      "Without measuring the right metrics, you're essentially creating content in the dark. Today we'll cover...",
  },
]

// Mock channels
export const mockChannels = [
  {
    id: "channel1",
    name: "Vercel",
    url: "https://www.youtube.com/c/VercelHQ",
    subscribedAt: "2023-01-15T12:00:00Z",
    videoCount: 42,
    transcriptionEnabled: true,
    transcriptionLimit: 5,
    lastSynced: "2023-05-01T08:30:00Z",
  },
  {
    id: "channel2",
    name: "Next.js",
    url: "https://www.youtube.com/c/NextJSconf",
    subscribedAt: "2022-11-05T15:20:00Z",
    videoCount: 28,
    transcriptionEnabled: true,
    transcriptionLimit: 3,
    lastSynced: "2023-04-28T14:15:00Z",
  },
  {
    id: "channel3",
    name: "Fireship",
    url: "https://www.youtube.com/c/Fireship",
    subscribedAt: "2022-08-22T09:45:00Z",
    videoCount: 156,
    transcriptionEnabled: false,
    transcriptionLimit: 5,
    lastSynced: "2023-04-30T22:10:00Z",
  },
]

export const mockMetadata = [
  {
    id: "meta1",
    name: "John Doe",
    description: "Expert in AI and Machine Learning",
    type: "person",
    source: "TechCrunch",
    videoUrl: "https://www.youtube.com/watch?v=xxxxxxxxxxx",
  },
  {
    id: "meta2",
    name: "TensorFlow",
    description: "Open-source machine learning framework",
    type: "tool",
    source: "Google AI Blog",
    videoUrl: "https://www.youtube.com/watch?v=yyyyyyyyyyy",
  },
  {
    id: "meta3",
    name: "AI in Healthcare",
    description: "A case study on AI applications in healthcare",
    type: "case_study",
    source: "MIT Technology Review",
    videoUrl: "https://www.youtube.com/watch?v=zzzzzzzzzzz",
  },
  {
    id: "meta4",
    name: "Use Case: Predictive Maintenance",
    description: "Using machine learning to predict equipment failure",
    type: "use_case",
    source: "Industry Week",
    videoUrl: "https://www.youtube.com/watch?v=aaaaaaaaaaa",
  },
  {
    id: "meta5",
    name: "Opportunity: AI-Driven Personalization",
    description: "Leveraging AI to personalize customer experiences",
    type: "opportunity",
    source: "Forbes",
    videoUrl: "https://www.youtube.com/watch?v=bbbbbbbbbbb",
  },
  {
    id: "meta6",
    name: "Risk: Algorithmic Bias",
    description: "Addressing bias in AI algorithms",
    type: "risk",
    source: "The Verge",
    videoUrl: "https://www.youtube.com/watch?v=ccccccccccc",
  },
  {
    id: "meta7",
    name: "Article Idea: The Future of Work",
    description: "Exploring the impact of AI on the job market",
    type: "article_idea",
    source: "Internal Brainstorm",
    videoUrl: "https://www.youtube.com/watch?v=ddddddddddd",
  },
]
